spring.application.name=ai_simulator
langchain4j.google-ai.gemini.api-key=AIzaSyAPkv6xvi36gHAji8XyxtCj_YzQNAzIBLs
langchain4j.google-ai.gemini.chat-model.model-name=gemini-2.5-flash
server.port=${PORT:8080}